#ifndef RETURN_CODE_H
#define RETURN_CODE_H

#define START_DELEGESC 10
#define STOP_DELEGESC 11
#define CAL_STOP_MON 12

#define TP_EDIT_REQ 40
 
#define MNGR_STOP_IF 50
#define TM_TYPE_INC 51
#define TM_TYPE_DEC 52
#define TM_WRITE_TASK 53
#define TM_UPDATE_IF_DAY_RANGE 54

#define SC_UPDATE_DATE_2_SUBM 100
#define SC_SWITCH_2_DS 101
#define SC_UNLOCK_TAB 102

#define TASKPANEL_ZERO_LEN 2000

#endif